### ISSUE TITLE
Contributions are welcome

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#1]
Currently, we have some unofficial implementations for C#. And maybe it's time to have an official one. I'm not sure if this code base is the best one, but suggestions are always welcome.

@xgenvn, can you help contribute to it?

@huazhikui, can you provide a to-do list?

**Comment by hsluoyz** [comment]
After discussing with @huazhikui , the current status for this project is: has the same functionality with jCasbin: https://github.com/casbin/jcasbin, test cases are also included.

TO-DOs:

1. Badges in README.md, including Travis CI, code coverage, Nuget, auto-generated docs (if any), code format, Gitter:

![image](https://user-images.githubusercontent.com/3787410/58892290-83b6a880-8720-11e9-8bf9-075a4b599734.png)

**Comment by xgenvn** [comment]
@hsluoyz Already fork the project, can't wait to have some time investing on first PR ;).

**Comment by huazhikui** [comment]
@xgenvn @hsluoyz 
TO-DO list:
1. Utl.LogPrint() method
2. CoreEnforcer.SetWatcher method  and  Implementation class of IWatcher interface;

**Comment by hsluoyz** [comment]
Hi @xgenvn , can you help fix the code coverage badge in README? https://github.com/casbin-net/Casbin.NET#casbinnet

**Comment by xgenvn** [comment]
> Hi @xgenvn , can you help fix the code coverage badge in README? https://github.com/casbin-net/Casbin.NET#casbinnet

I will take a look.

**Comment by xgenvn** [comment]
Have to move workplace recently so no actual work on the badge yet. I have tried to configure the current package (coveralls.net) plus opencover, then have some issues with local libraries not found. Will take a look at other libraries how they do this. Sorry for the late response.

**Comment by hsluoyz** [comment]
Hi @xgenvn , never mind. Thanks to @huazhikui, he had just made the badges work today :)
