### ISSUE TITLE
Pattern Matching in RBAC

### ISSUE THREAD

**Issue by mintyfusion** [casbin/Casbin.NET#10]
I have seen an example of Pattern Matching available here: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

I was wondering is it possible to do something like this in Casbin:

g, /specificgenre/book/:id, book_group

That means only books which are of specific genre are allowed access using pattern matching?

**Comment by hsluoyz** [comment]
What's the difference with `g, /book/:id, book_group`?

**Comment by mintyfusion** [comment]
I was confused, and this thread helped me: https://github.com/casbin/casbin/issues/177

This is what I'm trying to accomplish:

p, alice, /alice_data/*, GET
p, alice, /alice_data/resource1, POST

p, data2_admin, /alice_data/resource2, GET
p, data2_admin, /bob_data/*, (POST)|(UPDATE)
p, data2_admin, /bob_data/*/*/*/*, DELETE ==> Seems like Keymatch2 is the answer to this.

p, cathy, /cathy_data, (GET)|(POST)

g, alice, data2_admin

**Comment by hsluoyz** [comment]
Closed as solved.
