### ISSUE TITLE
The counterpart of GetImplicitUsersForPermission() in Casbin.NET is lacking

### ISSUE THREAD

**Issue by send2vinnie** [casbin/Casbin.NET#102]
The counterpart of GetImplicitUsersForPermission() in Casbin.NET is lacking in the API.

**Comment by hsluoyz** [comment]
@huazhikui @Sagilio

**Comment by Sagilio** [comment]
Thank your feedback，we will add this API later.

**Comment by hsluoyz** [comment]
Any update?

**Comment by Sagilio** [comment]
> Any update?

It will be fixed by #103.
