### ISSUE TITLE
use Casbin.NET is fail

### ISSUE THREAD

**Issue by Hareis** [casbin/Casbin.NET#104]
![image](https://user-images.githubusercontent.com/11290701/98626790-72c68980-234d-11eb-96dd-88fe050a91f4.png)

![image](https://user-images.githubusercontent.com/11290701/98626769-62aeaa00-234d-11eb-83e2-6cce634e1629.png)

i'm used 1.4.0

**Comment by hsluoyz** [comment]
@huazhikui @Sagilio

**Comment by Sagilio** [comment]
Thank your feedback, could you provide the sample model and policy files about this problem? I think It probably read an invalid model or policy.

**Comment by hsluoyz** [comment]
@Hareis

**Comment by Hareis** [comment]
``model``
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && ParamsMatch(r.obj,p.obj) && r.act == p.act

``policy``
p，10001，/api/Authority/CreateAuthority，POST

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by Sagilio** [comment]
@Hareis The `ParamsMatch` function is not a build-in function, you need to add it before calling Enforce.
Here is a little sample :
```csharp
public class ParamsMatchFunc : AbstractFunction
{
    public ParamsMatchFunc() : base(nameof(ParamsMatch))
    {
        
    }

    protected override Delegate GetFunc()
    {
        return new Func<string, string, bool>(ParamsMatch);
    }

    public static bool ParamsMatch(string obj1, string obj2)
    {
        // Your function content
        return true;
    }
}
```
And add this function by:
``` csharp
var paramsMatchFunc = new ParamsMatchFunc();
enforcer.AddFunction(paramsMatchFunc.Name , paramsMatchFunc);
```

We will provide more `AddFunction` overload in the future to make the function addition more convenient.

**Comment by Hareis** [comment]
tks, i changed that model file, i's success!
