### ISSUE TITLE
Implements CasbinJsGetPermissionForUser

### ISSUE THREAD

**Issue by elmankross** [casbin/Casbin.NET#105]
[Original issue from casbin.js](https://github.com/casbin/casbin.js/issues/19)
> Hello. According to my comment from docs it really will be helpful to implements CasbinJsGetPermissionForUser for .NET because of needs to use dynamic auth on the frontend.
~Idk it should be a derived library or a part of the existing one, but I think the first variant is better.~

Hello, .NET community, are there contributors can do this or it needs a PR? Thanks.

**Comment by hsluoyz** [comment]
@Sagilio @kingiw

**Comment by Sagilio** [comment]
I think we can add a new project named  `Casbin.Extension.Frontend` for this API, because it'll introduce a new dependency and is not that related to the main functionality of `Casbin.NET`. What do you think about it?

**Comment by hsluoyz** [comment]
@Sagilio , sure. I have set you as the owners of https://github.com/casbin-net , please create this repo under the Casbin.NET org.

**Comment by Sagilio** [comment]
> @Sagilio , sure. I have set you as the owners of https://github.com/casbin-net , please create this repo under the Casbin.NET org.

Okay

**Comment by hsluoyz** [comment]
@elmankross hi, can you make a PR to: https://github.com/casbin-net/extensions ?

**Comment by elmankross** [comment]
> @elmankross hi, can you make a PR to: https://github.com/casbin-net/extensions ?

Hi. Of course. How I got it, it only needs to support .Net 3.1 and .Net 5, right?

**Comment by hsluoyz** [comment]
@elmankross can we support .NET Framework 4.5 as well as Casbin.NET also supports it? https://github.com/casbin/Casbin.NET/issues/27#issuecomment-636603482

**Comment by elmankross** [comment]
> @elmankross can we support .NET Framework 4.5 as well as Casbin.NET also supports it? [#27 (comment)](https://github.com/casbin/Casbin.NET/issues/27#issuecomment-636603482)

Np, I think there will no platform related things. So, a frontend library will use .netstandard1.0 too 👍

**Comment by hsluoyz** [comment]
Great, thanks!

**Comment by elmankross** [comment]
> I think we can add a new project named `Casbin.Extension.Frontend` for this API, because it'll introduce a new dependency and is not that related to the main functionality of `Casbin.NET`. What do you think about it?

So, I understood right the [Extensions](https://github.com/casbin-net/extensions) repo is for extending ASP.NET projects with all related dependencies, such as Json and maybe something else?

**Comment by elmankross** [comment]
> > I think we can add a new project named `Casbin.Extension.Frontend` for this API, because it'll introduce a new dependency and is not that related to the main functionality of `Casbin.NET`. What do you think about it?
> 
> So, I understood right the [Extensions](https://github.com/casbin-net/extensions) repo is for extending ASP.NET projects with all related dependencies, such as Json and maybe something else?
Ok, I answer myself: It's no need to deal with ASP.NET dependencies and abstractions. There is a simple example of usage.
