### ISSUE TITLE
Casbin .NET doesn't support multiple evals

### ISSUE THREAD

**Issue by paoloamato2** [casbin/Casbin.NET#106]
I have tried many times, and i can surely say that if i use a policy like this:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = rule_sub, rule_obj, rule_act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.rule_sub) && eval(p.rule_obj) && eval(p.rule_act)
```

No matter what, casbin considers only the first eval.
Can you fix this please?
I already read about this problem, maybe it was not fixed for .net?

I have 1.4.0 version downloaded from nuget.
Thanks in advance.

@hsluoyz

**Comment by hsluoyz** [comment]
Can we fix it? @huazhikui @Sagilio

**Comment by Sagilio** [comment]
Thank you for your feedback, we will fix this issue as soon as possible.

**Comment by hsluoyz** [comment]
@paoloamato2 do you need a new release?

**Comment by paoloamato2** [comment]
it is not necessary for me
@hsluoyz

**Comment by mentapro** [comment]
Now I am using Casbin.NET 1.8.0 and I have save problem that only one `eval` is recognised. 
Can someone help me please, what is the problem? 
Is this bug fixed or am I doing something wrong? @hsluoyz

**Comment by Sagilio** [comment]
@mentapro This bug should have been fixed. Can you provide a test case with a sample model and policy files?

**Comment by mentapro** [comment]
@Sagilio Yes, of course.
I use NUnit for testing. Also Casbin.NET 1.8.0 installed. .NET 5.0.
I have such **test method**:
```
[Test]
public void Given_Enforce_When_ModelHasTwoEval_Then_IsAllowed()
{
    var enforcer = new Enforcer("model.conf", "policy.csv");
    var isAllowed = enforcer.Enforce(
        "domain1",
        new {Role = "admin"},
        new {Name = "admin_panel"},
        "view");
    Assert.That(isAllowed, Is.True);
}
```

Also, I have **model**:
```
[request_definition]
r = dom, sub, obj, act

[policy_definition]
p = dom, sub_rule, obj_rule, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.dom == p.dom && eval(p.sub_rule) && eval(p.obj_rule) && r.act == p.act
```
And **policy.csv** file (1-line csv file):
```
p, domain1, r.sub.Role == "admin", r.obj.Name == "admin_panel", view
```

But my test throws exception: 
`
DynamicExpresso.Exceptions.UnknownIdentifierException : Unknown identifier 'eval' (at index 43).
   at DynamicExpresso.Parsing.Parser.ParseIdentifier()
`
