### ISSUE TITLE
Return hitted policy from the Enforcer

### ISSUE THREAD

**Issue by mabvanaartrijk** [casbin/Casbin.NET#109]
Thanks for this great library! I have a question concerning the Cabin.NET implementation. Is there any way to return the hitted policy in the Enforcer? In the Go implementation I see that LogEnforce is able to log the hit policy, but I don’t see this in Casbin.NET. Is this correct and is there a way to do this?

**Comment by Sagilio** [comment]
Thank you, but this feature has not been implemented in the .NET version now, we will implement it in the next release.

**Comment by hsluoyz** [comment]
@mabvanaartrijk plz use `EnforceEx()`: https://github.com/casbin/Casbin.NET/pull/117
