### ISSUE TITLE
GetImplicitPermissionsForUser needs a (string name, params string[] domain) override.

### ISSUE THREAD

**Issue by jakobthordar** [casbin/Casbin.NET#112]
As the title says, the GetImplicitRolesForUser can take a domain as a second parameter. 
GetImplicitPermissionsForUser does not. It defaults to using no domain when doing the policy mapping later down the line.

**Comment by hsluoyz** [comment]
@Sagilio can you take a look at this issue?

**Comment by Sagilio** [comment]
> @Sagilio can you take a look at this issue?

Ok.

**Comment by Sagilio** [comment]
@jakobthordar The lack of override APIs has been added at PR #115. It will be included in the next release.

**Comment by hsluoyz** [comment]
@Sagilio you can make a new release on both Nuget.org and GitHub Releases.
