### ISSUE TITLE
Remove name as a first parameter to simplify code

### ISSUE THREAD

**Issue by jakobthordar** [casbin/Casbin.NET#113]
This is not exactly an "issue".
But this code could be simplified to only take in the function. AbstractFunction has a Name property which could be used in the code.

This makes it possible to also simplify IExpressionHandler.SetFunction by removing the name parameter. And instead using AbstractFunction.Name

https://github.com/casbin/Casbin.NET/blob/aa4fade2ac39b7315c8796c8937b4720c47bf797/NetCasbin/ManagementEnforcer.cs#L986

**Comment by hsluoyz** [comment]
@jakobthordar this is for API compatibility with other language like Go: https://casbin.org/docs/en/management-api#addfunction

Some langs like Go use "function pointer" instead of a struct/class like AbstractFunction with a "name" property. So we have to specify the name explicitly.

**Comment by Sagilio** [comment]
@hsluoyz  Actually, it should not receive an AbstractFunction type.
