### ISSUE TITLE
Version 1.2.2.and 1.2.3 dependency issue

### ISSUE THREAD

**Issue by rickdtully** [casbin/Casbin.NET#12]
I am evaluating Casbin.NET for my company. I have a visual studio 2019 ASP.NET core in .NET framework 4.7.2 project that i am attempting to use the Casbin.NET nuget package with. Version 1.2.0 installs and executes perfectly but 1.22 and 1.23 , though they install, result in an error when an Enforcer is instantiated. The error is "Could not load file or assembly 'DynamicExpresso.Core, Version=2.3.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)".

**Comment by hsluoyz** [comment]
@huazhikui

**Comment by huazhikui** [comment]
becasuse the DynamicExpresso.Core is not strongly-named assembly.  we will not provide strongly named assemblies by default in next. you can use version 1.2.4

**Comment by rickdtully** [comment]
Thank you, that works. BTW, your Casbin editor is extraordinarily helpful.

**Comment by hsluoyz** [comment]
@huazhikui @rickdtully @kyle-mccarthy 

please fix the build error: https://travis-ci.org/casbin/Casbin.NET/builds/622437945?utm_medium=notification&utm_source=email
