### ISSUE TITLE
Unique namespace specification

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#120]
A improvement in #101.

#### **Description**

Casbin has many extensions and it will more in the future, To avoid chaos we can provide a unique namespace specification suggestion.  It will like this :

##### **Core Abstractions => Casbin**

Sample: 
- "IEnforcer" full type are `Casbin.IEnforcer`.
- "IModel" full type are `Casbin.IModel`

##### **Core => Casbin.[Part Name]**

Sample: 
- "Assertion" full type is `Casbin.Model.Assertion`.
- "DefaultConfig" full type are `Casbin.Config.DefaultConfig`

##### **Extensions Abstractions => Casbin.Persist**

Sample: "IAdapter" full type is `Casbin.Persist.IAdapter`

##### **Extensions => Casbin.[Extension Type Name].[Extension Name]**

Sample: "EFCoreAdapter" full type are `Casbin.Adapter.EFCore.EFCoreAdapter`
Sample: "RaftDispatcher" full type are `Casbin.Dispatcher.Raft.RaftDispatcher`

#### **Changes**
Namespace changed (**Breaking Changes**):
- `NetCasbin.X` => `Casbin.X`
- `Casbin.NET.Adapter.EFCore` => `Casbin.Adapter.EFCore`

**Comment by hsluoyz** [comment]
sounds great to me!

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/Casbin.NET/pull/121
