### ISSUE TITLE
Extendibility structure Improve

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#124]
#### **Description**

Provide more interface and the default implement uses the unique `DefaultXXX` format to name. 
It like `IEffector` to `DefaultEffector` and `IRoleManager` to `DefaultRoleManager`

#### **Changes**

- Add `IModel`, `IConfig`, `IEnforcer`.
- Change the default implement class name to `DefaultConfig`and `DefaultModel`.
- Replace parameters type and return type with the interface.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/Casbin.NET/pull/136
