### ISSUE TITLE
ABAC with RBAC 

### ISSUE THREAD

**Issue by salamalzubedi** [casbin/Casbin.NET#14]
Hello 
Plaese I want to make access control model with ABAC and only role from RBAC. 
its will be only in C#. 
the idea is to test this model software in openstack . 
( access control model  in C# and its will test this kind of access control Policy in openstack if we move to openstack as SaaS)
Please any one could help me.

Thanks

**Comment by hsluoyz** [comment]
See some issues at Golang: https://github.com/casbin/casbin/issues?q=rbac+abac

**Comment by hsluoyz** [comment]
Closed as stale.
