### ISSUE TITLE
Casbin.NET v1.5.1 - incorrect File/Product version?

### ISSUE THREAD

**Issue by pavolsimon** [casbin/Casbin.NET#144]
Hi all;

I am using Casbin.NET.Adapter.EFCore 1.5.2 with NetCasbin 1.5.1, but it is throwing exception:
_Could not load file or assembly 'NetCasbin, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified._
NetCasbin 1.5.0 was working fine.

I believe it is related to assembly version, please, see below:
NetCasbin 1.5.0
File version 1.5.0.0
Product version 1.5.0
02/12/2021

NetCasbin 1.5.1
File version **1.0.0.0**
Product version **1.0.0**
03/19/2021

Thanks!

Pavol

**Comment by Sagilio** [comment]
It is a bug in the ci conf file, I will fix it later, thank you.

**Comment by Sagilio** [comment]
@pavolsimon  Could you have a try to use the v1.5.2 version?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/Casbin.NET/commit/19884d4a6020e0668e0df3e10a48219d089fb506

**Comment by pavolsimon** [comment]
@Sagilio Many thanks, now it is working as expected.
