### ISSUE TITLE
Get a list of domains for a user

### ISSUE THREAD

**Issue by thoraj** [casbin/Casbin.NET#146]
Is there a way to get a list/array of all domains where a user/subject has permissions. 

If this is not possible, does it make sense to add such a thing?

**Comment by hsluoyz** [comment]
@thoraj use `GetFilteredPolicy()` API: https://casbin.org/docs/en/management-api#getfilteredpolicy

**Comment by thoraj** [comment]
AFAICT GetFilteredPolicy() will only give the policies where the user is explicitly. I can extract the unique domains from this list, but it does not solve my problem. 

How can I get a list/array of all domains where a user/subject has permissions.

If a user has only been been granted a permissions indirectly because he has a role. There will be noe explicit policies which mentions the user (since all policies will have the role as the subject). 

I was hoping for a method similar to:

```
var domains = enforcer.GetDomainsForUser("userid")
```
And that this method returned all domains in which the user has an implicit/inherited permission (considering the role hierarchy)

Since there is no such method, I need to create the same result somehow
