### ISSUE TITLE
Getting a list of domains where a user has permissions

### ISSUE THREAD

**Issue by thoraj** [casbin/Casbin.NET#147]
AFAICT GetFilteredPolicy() will only give the policies where the user is explicitly. I can extract the unique domains from this list, but it does not solve my problem. 

How can I get a list/array of all domains where a user/subject has permissions.

If a user has only been been granted a permissions indirectly because he has a role. There will be noe explicit policies which mentions the user (since all policies will have the role as the subject). 

I was hoping for a method similar to:

```
var domains = enforcer.GetDomainsForUser("userid")
```
And that this method returned all domains in which the user has an implicit/inherited permission (considering the role hierarchy)

Since there is no such method, I need to create the same result somehow

_Originally posted by @thoraj in https://github.com/casbin/Casbin.NET/issues/146#issuecomment-806923154_

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by hsluoyz** [comment]
@Sagilio plz port it From Go to .NET: https://github.com/casbin/casbin/issues/744

**Comment by Sagilio** [comment]
@hsluoyz Ok.
