### ISSUE TITLE
Helper.LoadPolicyLine causes poor performance

### ISSUE THREAD

**Issue by arthuridea** [casbin/Casbin.NET#15]
I'm loading nearly 10000 policies in my project .
the Casbin core module and Adapter is injected as Scoped service.
I found this method checking policy uniqueness every time when data line loaded. I wrote a method 
``` C#
private void PolicyUniquenization(Model model)
        {
            var m = model.Model;
            foreach(var key in m.Keys)
            {
                foreach (var ast in m[key].Values)
                {
                    ast.Policy = ast.Policy.Distinct().ToList();
                }
            }
        }
```
then alter ```Helper.LoadPolicyLine``` method without checking data uniqueness.
and invoke at the end of LoadPolicy method in Adapter
``` C#
public void LoadPolicy(Model.Model model)
        {
            // some codes of polices loading...

            PolicyUniquenization(model);
        }
```` 
seems to make things better?
want to know if this modification causes any problem..

**Comment by hsluoyz** [comment]
@arthuridea I think your modification is reasonable.

@huazhikui can we fix this issue?

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain @nodece I think we can use a map to store the hash of existing policy. Checking the map is O(1) complexity.

@Sagilio can you work on this issue?

**Comment by xcaptain** [comment]
The problem may comes from here
```csharp
var content = tokens.Skip(1).ToList();
if (!model.HasPolicy(sec, key, content))
{
    policy.Policy.Add(content);
}
```
The `HasPolicy` check is slow, everytime a new policy is loaded into model, we need to check if it already exists.

using

```csharp
ast.Policy = ast.Policy.Distinct().ToList();
````
can improve a lot, how about we change

```csharp
public List<List<String>> Policy
```

to 

```csharp
public HashSet<List<String>> Policy
```

HashSet may be faster.

@Sagilio What do you think?

**Comment by xcaptain** [comment]
Haha, casbin-rs is using `indexset`

https://github.com/casbin/casbin-rs/blob/master/src/model/assertion.rs#L21

**Comment by Sagilio** [comment]
> The problem may comes from here
> 
> ```cs
> var content = tokens.Skip(1).ToList();
> if (!model.HasPolicy(sec, key, content))
> {
>     policy.Policy.Add(content);
> }
> ```
> 
> The `HasPolicy` check is slow, everytime a new policy is loaded into model, we need to check if it already exists.
> 
> using
> 
> ```cs
> ast.Policy = ast.Policy.Distinct().ToList();
> ```
> 
> can improve a lot, how about we change
> 
> ```cs
> public List<List<String>> Policy
> ```
> 
> to
> 
> ```cs
> public HashSet<List<String>> Policy
> ```
> 
> HashSet may be faster.
> 
> @Sagilio What do you think?

I think we can use `HashSet<T>` to replace the `List<T>` to get O(1) complexity when we call `Contain`.
But it needs the `List<string>` implement `Equal` and  `GetHashCode`. So I think we can try to use a `ref struct` or `readonly ref struct` named `Rule` to replace `List<string>`.

**Comment by xcaptain** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netcore-3.1

**Comment by Sagilio** [comment]
They are `Inherited from Object`, So the `Equals` is equivalent to calling the ReferenceEquals method,
I think we need to ensure the content is equal.
And I think we can create a benchmark project which uses [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet).
