### ISSUE TITLE
Using builtin or custom functions in rbac hierarchies

### ISSUE THREAD

**Issue by thoraj** [casbin/Casbin.NET#154]
I'm experimenting with various models, and I would like to use KeyMatchX functions in the rbac  hierarchies. 

I have a couple of questions: 
1. How can I make a rbac hierarchy use builtin or custom functions? 
1. How can I make different rbac hierarchies use different functions?

For 1. I have tried 

Model
``` ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _  	# users and role hierarchies
g2 = _, _		# organization hierarchies
g3 = _, _		# functional hierarchies

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.obj, p.obj) && g3(r.act, p.act) && r.dom == p.dom
```

Tests
``` csharp
       [Theory]

        // Client admins do NOT get permissions in their parent (customer)
        [InlineData("@adm1:verji.app", "org::customer1", "cust1", "manage", true)]
        public void CheckUseOfRbacFunctions(string sub, string dom, string obj, string act, bool result)
        {
            var e = new Enforcer("../../../Casbin/verji2-rbac-model.conf", "../../../Casbin/verji2x-test-policy.csv");
            var rm = new GroupRoleManager(5) { MatchingFunc = (arg1, arg2) =>
                {
                    Log.Information("Args:{a1} {a2}", arg1, arg2);
                    return arg1 ==arg2;
                }
            };

            e.SetRoleManager(rm);
            e.Enforce(sub, dom, obj, act).Should().Be(result);
        }
```
It does not seem that the MatchingFunction is called at all?  I have tried this with both the GroupRoleManager and the DefaultRoleManager.  And I could not find a way to set the function other than setting the rm.MatchingFunc property directly. 

It is also unclear if/how it is possible to set different matching functions for the different rbac hierarchies (g, g2, and g3)?
Or if the MatchingFunction only applies to **g** or all **g**, **g2** and **g3**

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by Sagilio** [comment]
Now, MatchingFunction and DomainMatchingFunc will call all hierarchies, because they will use the same role manager instance. 

I will add two APIs for this issue,：
```
public static Enforcer AddNamedMatchingFunc(this Enforcer enforcer, string roleType, Func<string, string, bool> func)
public static Enforcer AddNamedDomainMatchingFunc(this Enforcer enforcer, string roleType,  Func<string, string, bool> func);
```

You can use them like this:
```
enforcer.AddNamedMatchingFunc("g2", BuiltInFunctions.KeyMatch2);
```

**Comment by thoraj** [comment]
That sounds great. Looking forward to check this out 👍

But how can I test the current functionality? As mentioned I'm not able to use matchFunctions at all. With the current casbin.net, how do I tell the role manager to use builtin or custom function?

**Comment by Sagilio** [comment]
> That sounds great. Looking forward to check this out 👍
> 
> But how can I test the current functionality? As mentioned I'm not able to use matchFunctions at all. With the current casbin.net, how do I tell the role manager to use builtin or custom function?

You may need to call `e.BuildRoleLinks();` after the `e.SetRoleManager(rm);`.

**Comment by Sagilio** [comment]
@thoraj You can have a try the v1.7.0 version.

**Comment by thoraj** [comment]
@Sagilio Yes thanks, I am looking at it as we speak.  I will report back once I have finished 👍

**Comment by thoraj** [comment]
@Sagilio I have tested with a really simple model, but I'm a little puzzled by the result. Probably it is because of my wrong reasoning?
Model
``` csharp
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _  	# users and role hierarcies
g2 = _, _		# organization hierarchies
g3 = _, _		# functional hierarchies

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom)
```

Policy: 
``` csharp
// Policies

// role and functions to permissions
p, grp::system_admin, org::customer1, cust1, manage

//
// user => group mappings & group hierarchies
//
g, @adm-user, grp::system_admin, org::customer1

```
Test: 
``` csharp
        [Theory]
        [InlineData("@adm-user", "org::customer1", "cust1", "manage", true)]
        public void CheckUseOfRbacFunctions(string sub, string dom, string obj, string act, bool result)
        {
            var e = new Enforcer("../../../Casbin/verji2x-rbac-model.conf", "../../../Casbin/verji2x-test-policy.csv");
            var rm = new DefaultRoleManager(5);
            rm.AddMatchingFunc((arg1, arg2) =>
            {
                var gResult = arg1.Equals(arg2);
                Log.Information("GFunc({a1},{a2}) = {result}", arg1, arg2, gResult);
                return gResult;
            });

            e.SetRoleManager(rm);
            //e.BuildRoleLinks();
            e.Enforce(sub, dom, obj, act).Should().Be(result);
        }
```
I expect this test to pass since the matching func is a simple equality comparer. 

So when I reversed the logic to an _inequality_ comparer `var gResult = !arg1.Equals(arg2);` I expected the test to fail. But it did not. So apparently we get a match on the policy even with the compare logic reversed? 

Always returning false makes the test fail as expected: `var gResult =false;`

Is this a weird corner-case, or is this behavior expected?  

Or more likely, is my reasoning here flawed?

**Comment by thoraj** [comment]
@Sagilio I noticed the issue has been closed. Is anyone tracking this issue?

**Comment by hsluoyz** [comment]
@Sagilio plz follow up

**Comment by Sagilio** [comment]
> @Sagilio I noticed the issue has been closed. Is anyone tracking this issue?

See: #156
