### ISSUE TITLE
SavePolicy fails unless model contains [role_definition]

### ISSUE THREAD

**Issue by prasannapad** [casbin/Casbin.NET#16]
SavePolicy() method fails when trying to save basic_model.conf in the examples folder.

It works if you add this notionally.
[role_definition]
g = _, _

If roles are optional in the model, can we make sure SavePolicy() ignores missing g?

**Comment by hsluoyz** [comment]
Can you make a PR to fix it?

**Comment by hsluoyz** [comment]
Any update? @huazhikui @prasannapad

**Comment by AaqibAhamed** [comment]
I want to contribute for this bug as a GSoC 2020 student contributer.

**Comment by hsluoyz** [comment]
@huazhikui can anyone fix it?

**Comment by huazhikui** [comment]
@AaqibAhamed you like to try？fix this bug

**Comment by AaqibAhamed** [comment]
> @AaqibAhamed can you fix it?

@huazhikui Sure.I will try this. Thank you

**Comment by huazhikui** [comment]
@prasannapad the bug fixed in version 1.2.5
