### ISSUE TITLE
Change lowest TFM form net45 to net452

### ISSUE THREAD

**Issue by sagilio** [casbin/Casbin.NET#168]

**Comment by hsluoyz** [comment]
Why do this? This will drive away .NET 4.5 users.

**Comment by sagilio** [comment]
@hsluoyz  It only updates .NET Framework 4.5 to .NET Framework 4.5.2. 

Now Visual Studio 2022 can not install and build the 4.5 and 4.5.1 targets. I think we can consider updating this in the future.

In fact, .NET Framework 4.5 and 4.5.1 is ended the lifecycle very easily.
![image](https://user-images.githubusercontent.com/42855245/122930598-b337bc80-d39e-11eb-98d2-c915f55362a8.png)

**Comment by hsluoyz** [comment]
@xcaptain @huazhikui what about your ideas?

**Comment by Leonardo-Ferreira** [comment]
my 2 cents: very few people are still developing software targeting .net 4.5 to the point where you would be fixing bugs that they've encountered OR they would be adopting a new security-related library. In practical terms, changing from 4.5 to 4.5.2 impacts basically no one

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira thanks for the explanation!

@Leonardo-Ferreira @sagilio can anyone of you make a PR to upgrade to .net 4.5.2 ?

**Comment by hsluoyz** [comment]
@sagilio I saw this one: https://github.com/casbin/Casbin.NET/pull/169 , can you open it again?

**Comment by sagilio** [comment]
> @sagilio I saw this one: #169 , can you open it again?

ok

**Comment by hsluoyz** [comment]
Hi @sagilio , I found I can open it :) Can you fix the conflicts at: https://github.com/casbin/Casbin.NET/pull/169#issuecomment-966256452 ?

**Comment by Leonardo-Ferreira** [comment]
https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

radical idea: raise the bar on MAY 2022 to net 4.6.2. We could make a statement now, reenforcing it every N weeks... this would allow us to remove a lot of the the pragma directives because Microsoft.Extension.Logging v5.0.0 is supported on .net 4.6.1 and forward (https://www.nuget.org/packages/Microsoft.Extensions.Logging/5.0.0)

**Comment by Leonardo-Ferreira** [comment]
@sagilio @hsluoyz close this since it was achieved on another PR?

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira which PR?

**Comment by sagilio** [comment]
closed by #169
