### ISSUE TITLE
How to handle multi threading scenario when using Enforcer

### ISSUE THREAD

**Issue by twchiam** [casbin/Casbin.NET#17]
I noticed the .net version of casbin does not has the multi threading features.  May I know how should we use the enforcer in multi threading environment?

**Comment by twchiam** [comment]
Should I instantiate the enforcer only once and share the instance between all the requests?

**Comment by twchiam** [comment]
I am trying to understand the source code and below are my findings from the code:

1. I noticed the entire code base including the IAdapter interface do not use async await approach. The adapter might need to load data from the database especially the LoadPolicy method. Without async await, it might block execution  of  other request.

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain

**Comment by hsluoyz** [comment]
@twchiam can you make a PR to fix it?

ping @huazhikui again
