### ISSUE TITLE
Explicit priority model support

### ISSUE THREAD

**Issue by apiscevs** [casbin/Casbin.NET#179]
That would be really great to have an Explicit priority model support in Casbin.Net.

That feature was introduced approximately 4 months ago in the original Casbin written on Go and looks like starts to be adopted in other language ports. 

Two months ago it was added to jCasbin.
https://github.com/casbin/jcasbin/commit/36470f4d79e06b193ad5be5af70ba0ededc42b44#diff-f3cc874d67b29491c834d1608aa582eaf1fb8611e8d343924c2ec2aa09563d31

https://github.com/casbin/jcasbin/commit/6a40ed326051890bffcef934a23ed78f1a0450ae#diff-f3cc874d67b29491c834d1608aa582eaf1fb8611e8d343924c2ec2aa09563d31

**Comment by sagilio** [comment]
Ok, I will work on this issue now！
