### ISSUE TITLE
Avoid to clear model when exception thrown in LoadPolicy in IAdapter

### ISSUE THREAD

**Issue by sagilio** [casbin/Casbin.NET#183]
https://github.com/casbin/casbin/issues/791

**Comment by AsakusaRinne** [comment]
Hey, I think the problem may not exist in preview branch.

When I add test with the following code

```cs
[Fact]
        public void TestFailedToLoadPolicy()
        {
            var e = new Enforcer(TestModelFixture.GetNewTestModel(
                _testModelFixture._rbacWithDenyModelText,
                _testModelFixture._rbacWithDenyPolicyText));
            e.BuildRoleLinks();
            //e.AddNamedMatchingFunc(PermConstants.GroupingPolicyType2, BuiltInFunctions.KeyMatch2);
            TestEnforce(e, "alice", "data2", "read", true);
            TestEnforce(e, "bob", "data2", "write", true);
            try
            {
                e.SetAdapter(new FileAdapter("Not found"));
                e.LoadPolicy();
            }
            catch(System.Exception ex)
            {
                System.Console.WriteLine("Got exception.");
            }
            finally
            {
                TestEnforce(e, "alice", "data2", "read", true);
                TestEnforce(e, "bob", "data2", "write", true);
            }
        }
```

Though an exception was thrown, the test could past with no problem.

Could this indicate that this issue has been solved in preview branch?

**Comment by AsakusaRinne** [comment]
> Hey, I think the problem may not exist in preview branch.
> 
> When I add test with the following code
> 
> ```cs
> [Fact]
> public void TestFailedToLoadPolicy()
> {
>     var e = new Enforcer(TestModelFixture.GetNewTestModel(
>         _testModelFixture._rbacWithDenyModelText,
>         _testModelFixture._rbacWithDenyPolicyText));
>     e.BuildRoleLinks();
>     //e.AddNamedMatchingFunc(PermConstants.GroupingPolicyType2, BuiltInFunctions.KeyMatch2);
>     TestEnforce(e, "alice", "data2", "read", true);
>     TestEnforce(e, "bob", "data2", "write", true);
>     try
>     {
>         e.SetAdapter(new FileAdapter("Not found"));
>         e.LoadPolicy();
>     }
>     catch(System.Exception ex)
>     {
>         System.Console.WriteLine("Got exception.");
>     }
>     finally
>     {
>         TestEnforce(e, "alice", "data2", "read", true);
>         TestEnforce(e, "bob", "data2", "write", true);
>     }
> }
> ```
> 
> Though an exception was thrown, the test could past with no problem.
> 
> Could this indicate that this issue has been solved in preview branch?

Could you please help to see if the test above indicates the problem doesn't exist in the preview branch? @sagilio

**Comment by hsluoyz** [comment]
Fixed, see: https://github.com/casbin/Casbin.NET/pull/278#issuecomment-1246478923
