### ISSUE TITLE
No rollback of memory data when adapter throw exception

### ISSUE THREAD

**Issue by twchiam** [casbin/Casbin.NET#19]
In InternalEnforcer.cs, there are 3 methods add or remove policy data. All these methods will add or delete data in memory first then call adapter to perform the mutation of data in data store behind the adapter.

It will cause data inconsistency issue if no revert or rollback logic in all those methods. Please refers to the  bold area of the partial code below: 

```c#
bool ruleAdded = model.AddPolicy(sec, ptype, rule);
if (!ruleAdded)
{
    return false;
}

if (adapter != null && autoSave)
{
    try
    {
        await adapter.AddPolicyAsync(sec, ptype, rule);
    }
    catch (NotImplementedException)
    {
    }
    catch (Exception e)
    {
       **// rollback logic to revert the related memory data**
        throw e;
    }

    if (watcher != null)
    {
        // error intentionally ignored
        watcher.Update();
    }
}
```

**Comment by hsluoyz** [comment]
Casbin.NET follows Golang's Casbin's work flow. So please send a GitHub issue to: https://github.com/casbin/casbin/blob/master/internal_api.go#L22 first

**Comment by AaqibAhamed** [comment]
I have go through GoLang's work flow.I have following doubts.
```
if !ruleAdded {
		return ruleAdded, nil
	}
```
it says if not equal to ruleAdded return  become true or not ?? What does ruleAdded mean?

**Comment by DivyPatel9881** [comment]
This control structure means, that if ```ruleAdded``` is false, it means if the rule is not added to the memory, the function ```returns false, nil(error)```.

**Comment by AaqibAhamed** [comment]
> This control structure means, that if `ruleAdded` is false, it means if the rule is not added to the memory, the function `returns false, nil(error)`.
@DivyPatel9881 
Now clear.Thanks for the response.

**Comment by AaqibAhamed** [comment]
> In InternalEnforcer.cs, there are 3 methods add or remove policy data. All these methods will add or delete data in memory first then call adapter to perform the mutation of data in data store behind the adapter.
> 
> It will cause data inconsistency issue if no revert or rollback logic in all those methods. Please refers to the bold area of the partial code below:
> 
> ```cs
> bool ruleAdded = model.AddPolicy(sec, ptype, rule);
> if (!ruleAdded)
> {
>     return false;
> }
> 
> if (adapter != null && autoSave)
> {
>     try
>     {
>         await adapter.AddPolicyAsync(sec, ptype, rule);
>     }
>     catch (NotImplementedException)
>     {
>     }
>     catch (Exception e)
>     {
>        **// rollback logic to revert the related memory data**
>         throw e;
>     }
> 
>     if (watcher != null)
>     {
>         // error intentionally ignored
>         watcher.Update();
>     }
> }
> ```
Why not catching for NotImplementedException ? Don't we need to show at lease error message ?

**Comment by hsluoyz** [comment]
I think we agreed on updating adapter first, then update memory in Golang: https://github.com/casbin/casbin/issues/415#issuecomment-642372336. Let's follow the similar pattern in .NET. Can anyone make a PR for it?

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain @sagilio @twchiam can you work on this one?

**Comment by hsluoyz** [comment]
@twchiam merged in: https://github.com/casbin/Casbin.NET/pull/28
