### ISSUE TITLE
PlatformTarget - x64

### ISSUE THREAD

**Issue by PanzerHabba** [casbin/Casbin.NET#20]
Hi,

Why is PlatformTarget set to x64 ?
In my project-configuration I have set this to "Any CPU". I then get a build-warning:

Warning	MSB3270	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\nomha4\.nuget\packages\casbin.net\1.2.4\lib\netstandard2.0\NetCasbin.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

Will it not build on other platforms ?

**Comment by hsluoyz** [comment]
Hi @PanzerHabba , it seems to be a bug. Can you make a PR to fix it?

**Comment by PanzerHabba** [comment]
Hi @hsluoyz , I can do that. But it seems like I`m not allowed to create feature-branches. Could you give me the permission ?

**Comment by hsluoyz** [comment]
You should create new branch or use master in your forked repo. Then fire a PR to us. We will review and merge to our master if OK.

**Comment by hsluoyz** [comment]
PR merged.
