### ISSUE TITLE
Invalid policy size: expected 3, got 6.

### ISSUE THREAD

**Issue by yaobo-lab** [casbin/Casbin.NET#215]
i use  EFCore-Adapter

mysql table record is

![image](https://user-images.githubusercontent.com/21329253/131479462-356a221e-6a95-4361-9527-91809ba977c7.png)

acl_model.conf:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)`
```

when is use
` _enforcer.EnforceAsync(uid, api, httpMethod);`

it throw a err:
`Invalid policy size: expected 3, got 6.`

**Comment by sagilio** [comment]
The reason for this problem is that the length of the array of each policy in the model is not 3. Can you confirm the content of this object?
```csharp
e.GetModel().Model["p"]["p"].Policy[0]
```

**Comment by hsluoyz** [comment]
@yaobo-lab you should set values of V3, V4 and V5 to `null` in DB.

**Comment by yaobo-lab** [comment]
> @yaobo-lab you should set values of V3, V4 and V5 to `null` in DB.

thx a lot!
