### ISSUE TITLE
EF-Adapter needs to be developed

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#23]
https://github.com/casbin-net/EF-Adapter

**Comment by AaqibAhamed** [comment]
I want to develop Entity Framework Adapter for Casbin.NET as a  GSoC 2020 student.I have completed internship as a .NET developer(ASP.NET MVC -Trainee .NET Developer )

**Comment by AaqibAhamed** [comment]
> https://github.com/casbin-net/EF-Adapter
Hi @hsluoyz ,
I have initialized the EF-Adapter project.I have given PR find it.I'm working on it.Also looking forward my upcoming PR for EF-Adapter .

**Comment by AaqibAhamed** [comment]
@hsluoyz 
Also Please create a Road Map for EF-Adapter it helps to go further.

**Comment by hsluoyz** [comment]
See EFCore's roadmap: https://github.com/casbin-net/EFCore-Adapter/issues/2

**Comment by hsluoyz** [comment]
@Sagilio whether do we still need to develop this adapter? What do you think?

**Comment by Sagilio** [comment]
> @Sagilio whether do we still need to develop this adapter? What do you think?

I think It like the `ASP.NET` and no longer being actively developed. We can implement at more popular platforms, like `Redis` `MongoDB` or `Dapper` etc. first.

**Comment by hsluoyz** [comment]
OK. The official docs (https://docs.microsoft.com/en-us/ef/efcore-and-ef6/#ef6) said:

`
Entity Framework 6 (EF6) is an object-relational mapper designed for .NET Framework but with support for .NET Core. EF6 is a stable, supported product, but is no longer being actively developed.
`

I will close this issue for now.
