### ISSUE TITLE
feat: Add globMatch to BuildInFunctions

### ISSUE THREAD

**Issue by dviry** [casbin/Casbin.NET#231]
Using Casbin.NET v1.11.0 - getting the following error when trying to use globMatch() as a matcher:
```
DynamicExpresso.Exceptions.UnknownIdentifierException: 'Unknown identifier 'globMatch' 
```

In the past I've used [DotNet.Glob](https://github.com/dazinator/DotNet.Glob) - can we integrate it as a built-in function?

Thanks in advance

**Comment by dviry** [comment]
PS: currently I'm adding it dynamically to the Enforcer instance:
```c#
enforcer.AddFunction("globMatch", (string key1, string key2) => Glob.Parse(key2).IsMatch(key1));
```

**Comment by hsluoyz** [comment]
@sagilio any comment?

@dviry can you make a PR?
