### ISSUE TITLE
Q: Casbin 1 vs 2

### ISSUE THREAD

**Issue by fubar-coder** [casbin/Casbin.NET#236]
TL/DR: Should I use Casbin 1 or 2?

The latest update for V2 happened in 2021-08, while the latest V2 update just happened a couple of days ago and this poses some questions:

- Is there a release plan for V2?
- Is V2 in its current state abandoned?
- Should I start with V1?
  - How difficult will the transition from V1 to V2 be?

**Comment by sagilio** [comment]
1. v2 has released most of the planned features, the last feature is still under development （https://github.com/casbin/Casbin.NET/pull/230)， we plan to release the RC branch next month.
2. No, V2 still working, it is necessary for future development and has a lot of necessary refactorings.
3. It not very plenty of public API changes from v1 to v2, here is a guide about it (https://github.com/casbin/Casbin.NET/wiki/Migrate-from-Casbin.NET-v1.x-to-v2.0).

**Comment by fubar-coder** [comment]
Thank you for your answer!
