### ISSUE TITLE
[Question] How to to call Enforce in Casbin.NET 2.0.0 preview?

### ISSUE THREAD

**Issue by shayura** [casbin/Casbin.NET#240]
I can't find any examples in the UnitTest projects, so I'm not sure how to migrate `Enforce(Async)` calls from the previous version. I would like to use `EnforcerContext` to switch between `p` and `p2` rules.

**Comment by shayura** [comment]
Please forgive me for the silly question. I have just found out about the extension methods `NetCasbin/Extensions/Enforcer/EnforcerExtension.cs`. I'll try using this newfound knowledge to call the enforcer to check `p2` rules.

**Comment by sagilio** [comment]
Maybe this is helpful to you: https://github.com/casbin/Casbin.NET/blob/e0af5c3bea91e9aa011eae85ff582ca7d0a2ca82/NetCasbin.UnitTest/ModelTests/ModelTest.cs#L564-L604
