### ISSUE TITLE
InvalidOperationException: Collection was modified

### ISSUE THREAD

**Issue by martinbolco** [casbin/Casbin.NET#244]
Hi All,

by looking at our logs we noticed repeating issues with collections being modified in couple of methods inside Casbin.NET library. See please the screenshots from the logs:

![image](https://user-images.githubusercontent.com/46045835/155527581-317bae79-e09c-4023-b273-b652b869539d.png)

![image](https://user-images.githubusercontent.com/46045835/155527766-0a9d9009-f71c-4600-90cd-5a0bb982e554.png)

Can somebody please take a look at it?

Thank you,

Martin

**Comment by sagilio** [comment]
The model at Casbin.NET v1 is not thread-safe default, please make sure synchronous call model instance.

You can try to use `SyncedEnforcer.Create()` to create an enforcer instance at Casbin.NET v2.

**Comment by martinbolco** [comment]
Thank you for the info. As I can see v2 is still in the preview. When do you plan to release standard version?

**Comment by hsluoyz** [comment]
@martinbolco v2 has been released, latest is v2.1.1: https://github.com/casbin/Casbin.NET/releases
