### ISSUE TITLE
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by martinbolco** [casbin/Casbin.NET#245]
Hi All,

we are experiencing issues with concurrent update on the collections inside Casbin.NET library. See please the log:

![image](https://user-images.githubusercontent.com/46045835/155529322-6c63e4cc-fa32-40e5-8b77-59a356326d0c.png)

Can somebody please take a look?

Thank you,

Martin

**Comment by sagilio** [comment]
It is the same question as #244
