### ISSUE TITLE
Handle paths with System.IO.Path

### ISSUE THREAD

**Issue by LuisPodestaGrip** [casbin/Casbin.NET#246]
The path variables in the Enforcer constructor handle everything as relative paths.

This change will help to use files from cloud storage or other sources that isn't in the project folder.

**Comment by hsluoyz** [comment]
@sagilio

**Comment by sagilio** [comment]
I have written a simple test for this issue, lt may already support relative paths. Could you write a sample unit test for your case?
```csharp
[Fact]
public void TestEnforceWithRelativePath()
{
    var e = new Enforcer("./examples/basic_model.conf");
    Assert.NotNull(e.GetModel());
}
```
![image](https://user-images.githubusercontent.com/42855245/157892243-0293fe50-a422-43f8-9c26-d8734f091ad8.png)

**Comment by hsluoyz** [comment]
Closed as stale
