### ISSUE TITLE
Use exist well-established configurion parser

### ISSUE THREAD

**Issue by sagilio** [casbin/Casbin.NET#264]
the model file is a standard `ini` format, we can use the existing configuration interface to more easily to integrate to .NET.

ref:
https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Ini
#263 
#258

**Comment by hsluoyz** [comment]
@sociometry

**Comment by hsluoyz** [comment]
@sagilio will this std lib API align with our commenting style? https://casbin.org/docs/en/syntax-for-models#docsNav:~:text=A%20model%20CONF%20can%20contain%20comments.%20The%20comments%20start%20with%20%23%2C%20and%20%23%20will%20comment%20the%20rest%20of%20the%20line.

**Comment by sagilio** [comment]
@hsluoyz Yes, they have the same style.
