### ISSUE TITLE
We should focus on the issues created by users first

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#268]
Hi @sagilio @sociometry @AsakusaRinne

I found most of the issues are created by our own members. This is not a bad thing, but it may result in that we play by ourselves and have ignored the real user requirements, like:

![image](https://user-images.githubusercontent.com/3787410/175576475-0b98bd2d-612f-4d86-9cce-46c2964e2041.png)

So can we focus on the issues created by users first?

**Comment by sagilio** [comment]
In fact, we always work on these issues first, and all have been answered and resolved.

**Comment by hsluoyz** [comment]
sounds great! Thanks for the answer!
