### ISSUE TITLE
support .net framwork?

### ISSUE THREAD

**Issue by LeiYangGH** [casbin/Casbin.NET#27]
I'm using .net4.5 and trying to install it via nuget. The lowest version is 1.1.0. and it says requires .net standard2.0.

The question is why doesn't is support .net 4.5(.netstandard1.0)? As far as I know many dotnet core libraries also support .net framework.

**Comment by hsluoyz** [comment]
@huazhikui @nodece @GopherJ

**Comment by nodece** [comment]
We can use `.NET Standard 1.2`  and It can support `.NET Framework 4.5.1`.

See https://docs.microsoft.com/en-us/dotnet/standard/net-standard for detail.

**Comment by hsluoyz** [comment]
.net 4.5(.netstandard1.0) is still widely used. If we haven't used advanced features, we should change compatible level to: .net 4.5(.netstandard1.0)

**Comment by LeiYangGH** [comment]
yes.
I also tried re-targeting to .net framework 4.6.1(lowest of .netstandard2.0), but then I got a lot of warnings (Consider app.config remapping of assembly with no app.config mapping ...), and didn't find a elegant solution to fix them. so expecting casbin.net to support .net 4.5.

**Comment by hsluoyz** [comment]
I have asked an issue in our expression evaluator: https://github.com/davideicardi/DynamicExpresso/issues/120

**Comment by huazhikui** [comment]
casbin.net  support .net 4.5 in version 1.2.6
