### ISSUE TITLE
Fix CI error: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#296]
See: https://github.com/casbin/Casbin.NET/actions/runs/3087920959/jobs/4993888459

![image](https://user-images.githubusercontent.com/3787410/191213003-573b0574-b529-4125-ac19-a630304d8f21.png)

**Comment by hsluoyz** [comment]
@AsakusaRinne 

/cc @sagilio

**Comment by AsakusaRinne** [comment]
It was also mentioned [here](https://github.com/casbin/Casbin.NET/pull/285#issuecomment-1244854679) that the non-concurrent dictionary of cache of the new version raises exception when using ```ParallelBatchEnforce```. I'll try to fix it.

**Comment by sagilio** [comment]
close by #297

**Comment by choby** [comment]
Can this bug be fixed in version 1.x ?
