### ISSUE TITLE
Fix CI error

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#304]
https://github.com/casbin/Casbin.NET/actions/runs/3391970065

![image](https://user-images.githubusercontent.com/3787410/199939775-d8878f01-17e2-4cfa-bf06-3c79fa79962e.png)

**Comment by hsluoyz** [comment]
@sagilio

**Comment by sagilio** [comment]
Compatibility problem of .NET 7 RC2, I will fix it later.

![image](https://user-images.githubusercontent.com/42855245/199940145-028abbe2-3407-48ec-ab6e-3cf205d0d6df.png)

**Comment by sagilio** [comment]
Fixed now
![image](https://user-images.githubusercontent.com/42855245/203546167-71cb9b39-4fca-4c41-aa02-8c5ef1241dc5.png)
