### ISSUE TITLE
An expression cannot be used in this context because it cannot be passed or returned by reference

### ISSUE THREAD

**Issue by ZhengLin-Li** [casbin/Casbin.NET#306]
Interested in this!!

I am new to this project, and during my set up process for this project, my Rider IDE warns me the following message: `An expression cannot be used in this context because it cannot be passed or returned by reference`. However, I can successfully build this project. 

So, I just want to clarify if this is a potential issue that we need to fix? If so, I'd like to give it a try.

![image](https://user-images.githubusercontent.com/63448884/210140709-a5148ed3-1665-470c-941d-94859bb2269d.png)

**Comment by nomeguy** [comment]
@ZhengLin-Li can you join the QQ group: 546057381 ?

**Comment by sagilio** [comment]
This warning may not effect the build result, but I will fix it later.

**Comment by ZhengLin-Li** [comment]
> @ZhengLin-Li can you join the QQ group: 546057381 ?

already requested，please let in, thank you.
