### ISSUE TITLE
Does using Casbin.NET support defining multiple M's in matchers? For example, m1 m2

### ISSUE THREAD

**Issue by qq1176914912** [casbin/Casbin.NET#309]
When I configure the following figure in the conf file：
![image](https://user-images.githubusercontent.com/79817742/209519690-a8ecc672-8f1f-477f-967e-38de8d969d65.png)
Error will be displayed: can not find the assertion at the section m and policy type m. 。
I don't know if. net temporarily doesn't support defining multiple M's in matchers, or if my writing is wrong.
![image](https://user-images.githubusercontent.com/79817742/209519903-ab9d43fb-f487-4815-931d-035e34674b6f.png)

**Comment by hsluoyz** [comment]
@qq1176914912 this feature needs to be ported from Go to .NET

/cc @sagilio

**Comment by sagilio0728** [comment]
Casbin,NET supports this feature, you can see the example here: https://github.com/casbin/Casbin.NET/blob/9cecadd615760838691e391150e1384c1ed9c560/Casbin.UnitTests/ModelTests/ModelTest.cs#L562-L602

**Comment by sagilio0728** [comment]
close by https://github.com/casbin/Casbin.NET/pull/194
