### ISSUE TITLE
Fix or remove Travis CI because it doesn't support .NET Framework

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#31]
See: https://travis-ci.org/casbin/Casbin.NET

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain @nodece @Sagilio can anyone take this issue? Fix or remove?

**Comment by Sagilio** [comment]
I think we need not it now.

**Comment by hsluoyz** [comment]
@Sagilio so you think it's OK to remove it?

**Comment by Sagilio** [comment]
> @Sagilio so you think it's OK to remove it?

Yes

**Comment by hsluoyz** [comment]
Can you make a PR to remove it?
