### ISSUE TITLE
Where can I find ASP.NET 6 examples?

### ISSUE THREAD

**Issue by ZedZipDev** [casbin/Casbin.NET#311]
I'd like to find examples to check how to use Casbin.NET in NET6 Web Services. Are they somewhere?

**Comment by hsluoyz** [comment]
@sagilio

**Comment by AsakusaRinne** [comment]
Hi, maybe you the examples [here](https://github.com/casbin-net/casbin-aspnetcore/tree/master/samples) is what you wanted.

**Comment by ZedZipDev** [comment]
This example does not work, I have created an issue there
https://github.com/casbin-net/casbin-aspnetcore/issues/58

**Comment by ZedZipDev** [comment]
The question is: how to use Casbin.NET in NET 6 applications? What service(s), extension(s) need to add?

**Comment by ZedZipDev** [comment]
@AsakusaRinne Thank you. I have tried, but they do not work, I have added an issue 
https://github.com/casbin-net/casbin-aspnetcore/issues/58

**Comment by hsluoyz** [comment]
@ZedZipDev the issue: https://github.com/casbin-net/casbin-aspnetcore/issues/58 has been fixed. So this issue has also been resolved.
