### ISSUE TITLE
Check collection in ABAC with policy

### ISSUE THREAD

**Issue by resah** [casbin/Casbin.NET#312]
Hi, I am using ABAC with policy and wanted to check, if the user has a necessary claim for a resource property. Something like

```csv
p, r.obj.Group in r.sub.Claims, create
p, r.obj.Group in r.sub.Claims && r.sub.Name == r.obj.CreatedBy, delete
```

Is this possible? Should `r.sub.Claims` then be an array, enumerable, list, ...?

**Comment by sagilio** [comment]
@resah It will work, and the `r.sub.Claims` should be an `IEnumerable` at least.

**Comment by hsluoyz** [comment]
Closed as resolved
