### ISSUE TITLE
Apply politic to objects of different class going to excaption, but in posible in Go version 

### ISSUE THREAD

**Issue by palich12** [casbin/Casbin.NET#316]
When I try use some politic for excluded attribute/ For example, if try apply ruses for list of different classes objects, end some objects haven't used fields, I get exaptation. But it is correctly situation for Go library.

**Comment by palich12** [comment]
> May I ask which version you are using in your project? Do you mean to pass some `Object` of the different class to the `Enforce` method?

I use 1.13.0 version. I get it when write in policy some field, that out of class of my objects

**Comment by sagilio** [comment]
> 

Could you provide a sample or test case about this issue?
