### ISSUE TITLE
Add Azure Pipelines CI badge, maybe deprecate others in future

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#32]
We know .NET is from Microsoft. Azure Pipelines is also from Microsoft. So using Azure Pipelines as our CI will show strong credit that our code is well tested.

Moreover, our evaluator is also using it: https://github.com/davideicardi/DynamicExpresso

![image](https://user-images.githubusercontent.com/3787410/84374525-ab343100-ac10-11ea-9439-802b776f96f9.png)

So we should add a CI badge for Azure Pipelines. Maybe other CI badges will be deprecated in future.

**Comment by hsluoyz** [comment]
@huazhikui @nodece @xcaptain @Sagilio can anyone take this issue?

**Comment by Sagilio** [comment]
I can do it, but I need permission to visit the `Azure DevOps`. You can use `Sagilio@outlook.com` to invite me at `Azure DevOps`.

**Comment by huazhikui** [comment]
one month ago, I has added `Microsoft. Azure Pipelines`  ，but i have not add CI badges @Sagilio @hsluoyz 
https://dev.azure.com/Casbin/Casbin.NET/_build?view=pipelines

**Comment by hsluoyz** [comment]
@huazhikui great news to hear!

@Sagilio can you make a PR to add the badge for: https://dev.azure.com/Casbin/Casbin.NET/_build?view=pipelines ?

**Comment by hsluoyz** [comment]
@Sagilio you can also remove Appveyor totally in the new PR.

**Comment by Sagilio** [comment]
> @Sagilio you can also remove Appveyor totally in the new PR.

We need Appveyor to provide `Coverage Status` now.

**Comment by hsluoyz** [comment]
OK. Then we only add the Azure Pipelines badge for now.

**Comment by hsluoyz** [comment]
> one month ago, I has added `Microsoft. Azure Pipelines` ，but i have not add the CI badge @Sagilio @hsluoyz
> https://dev.azure.com/Casbin/Casbin.NET/_build?view=pipelines

@huazhikui can you add my Microsoft account: `hsluoyz@163.com` to the admin of the Casbin org in DevOps? https://dev.azure.com/Casbin/

![image](https://user-images.githubusercontent.com/3787410/84586370-a0b1ab80-ae4b-11ea-81fe-e6b2a36818c6.png)
