### ISSUE TITLE
Cannot get Policy with null value in EF core Adapter.

### ISSUE THREAD

**Issue by vansangnguyen1998** [casbin/Casbin.NET#335]
I am implemented Authorization with casbin in my dotnet project. I use EF core adapter for casbin and sql server to database.
My model.conf:
```
[request_definition]
r = RoleId, domain, TypeQuery, operationName

[policy_definition]
p = RoleId, domain, TypeQuery, operationName, eft, scope

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.RoleId, p.RoleId, r.domain) && r.domain == p.domain && r.TypeQuery == p.TypeQuery && r.operationName == p.operationName
```

I have the fake policy in sql server similar like that:
![image](https://github.com/casbin/Casbin.NET/assets/44341211/0d2743c8-b276-487e-a93d-256a1a685a6b)

When I call request to check permission for pipeline request: 
![image](https://github.com/casbin/Casbin.NET/assets/44341211/05344b01-d0cc-476e-94d5-3199b81e52e5)

But data when e.GetPolicy() only return 2 item with v5 is not null 
![image](https://github.com/casbin/Casbin.NET/assets/44341211/342466bf-6ff3-47a9-9fc2-99221d386da3)

Please help me solve problem with casbin.

I want to e.GetPolicy() have to have 3 policy contain record v5 is null

**Comment by hsluoyz** [comment]
@vansangnguyen1998 please:

1. Use pure Casbin API (enforcer, adapter, etc.) in the code (don't add your RESTful)
2. Clarify what you get and what you expect

**Comment by vansangnguyen1998** [comment]
@hsluoyz 
With my models.conf above.
When use e.GetPolicy()
I get response **2 record**: 
- invoice, app, q, getInvoice, allow, 1
- invoice, app, q, getInvoice, allow, 234
My expect have to exists 3 record
2 record **2 above and 1 record with v5 null** same image above ticket.
- invoice, app, q, getInvoice, allow
https://user-images.githubusercontent.com/44341211/272850597-0d2743c8-b276-487e-a93d-256a1a685a6b.png

**Comment by sagilio** [comment]
This should be related to the SQL generated by the policy. I will try to reproduce it later.

**Comment by vansangnguyen1998** [comment]
@sagilio 
I have reproduce with NodeJS with the same case, same data, and same model, I can get all policy with the same my expectation (3 policy).
Please check again with CasbinNodeJS ([Node Cas](https://github.com/casbin/node-casbin)) and Casbin-Dotnet

please reproduce with dotnet ASAP help me.
Thanks all

**Comment by hsluoyz** [comment]
@vansangnguyen1998 if your problem is for one adapter, create issue in that adapter's repo, not here

**Comment by dacongda** [comment]
it seems that adapter is not the problem, the question is cause by function ValuesFrom in model/policy.cs, it use string.IsNullOrWhiteSpace to valid weather the field is exist , so when the field is blank , it will return false and not appears in the result
