### ISSUE TITLE
Enforcer hangs during multi-threaded modifications

### ISSUE THREAD

**Issue by v-loboda** [casbin/Casbin.NET#336]
Hi guys

We encountered a problem in an environment where intensive policy modification occurs. It's very difficult to reproduce, and I can't do it reliably.
We have rbac model, several nodes with synchronization via IWatcher and a lot of policy changes including removing them.

Sometimes, very rarely, we catch an error
`Error Write lock may not be acquired with read lock held. This pattern is prone to deadlocks. Please ensure that read locks are released before taking a write lock. If an upgrade is necessary, use an upgrade lock in place of the read lock.`

From my point of view, there are 3 problem pleces:
1. DefaultPolicyStore.Node class, where PolicyTextSet collection can be changed from different threads in several places
2. Casbin.Rbac.Role class where _roles collection can be changed from different threads
3. InternalEnforce class and the InternalEnforce method, where Scanner.Interrupt is not executed on every execution path. This can lead to a deadlock in the internal Iterator->node.Lock, where after _node.Lock.EnterReadLock ExitReadLock will not be executed.

**Comment by sagilio** [comment]
Thank you for your feedback. I will review your points later and it would be helpful if you could provide more details like the error throw line.

**Comment by v-loboda** [comment]
This happen in the Default PolicyStore.Node class in TryAddPolicy and TryRemovePolicy, lines 74 and 133 respectively.

**Comment by hsluoyz** [comment]
@sagilio

**Comment by dmolochnikov** [comment]
Hello! Any updates on this issue?

**Comment by hsluoyz** [comment]
@v-loboda @dmolochnikov can you provide stable reproduce steps? and also:

1. Casbin.NET version?
2. Related code (like a test case)
3. Casbin model
4. Casbin policy

**Comment by v-loboda** [comment]
Hi, as I said before, it is hard to reprocude becase of multithreaded nature. You just need to modify your policies in several threads and read them simultaneously. In the first message I have pointed out several places that do not meet the multithreading requirements.

1. It was 2.1.1 version
2. There is no specific code, just multithreaded operations with AddPoliciesAsync, AddRoleForUserAsync, RemovePolicyAsync, EnforceAsync and GetImplicitPermissionsForUser
3. 
`
[request_definition]
r = sub, resource_type, resource, act

[policy_definition]
p = sub, resource_type, resource, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && (r.resource_type == p.resource_type || p.resource_type == "*") && (r.resource == p.resource || p.resource == "*") && (r.act == p.act || p.act == "*")
`
4. Policy pattern: ["user1", "test1", "test1", "test1"]

**Comment by hsluoyz** [comment]
@v-loboda how to reproduce it stably?

**Comment by v-loboda** [comment]
I would make a test case if I could reproduce the bug reliably.

I was able to reproduce it several times by running the modification and receiving permissions in multiple threads and waiting for errors for a long time. Sometimes the error appeared within a few seconds.

**Comment by seanamorosoamtote** [comment]
I definitely see similar issues. I didn't reproduce the deadlocking in a test yet, but I am seeing it as well.  However, The PR I submitted here handles some issues as well as a test case that would fail prior in the same vein of concurrent access issues.  https://github.com/casbin/Casbin.NET/pull/361

I would urge the team to investigate all usages of HashSet<string> reading and writing as they are not thread safe.

**Comment by hsluoyz** [comment]
If you cannot reproduce it, it cannot be fixed.

**Comment by sagilio** [comment]
I believe this issue is indeed possible to occur. The problem is likely due to changes being made to the same Node while the Scanner is not interrupted. I will continue to try to find a way to reliably reproduce it, and once I find it, I will reopen this issue.

During the discussion, there are other potential issues, I will create a new issue to link them.
