### ISSUE TITLE
How to return a custom type instead of using IQueryable type in IPolicyFilter

### ISSUE THREAD

**Issue by Muzi999** [casbin/Casbin.NET#344]
I am currently writing a custom adapter to support SqlSugar. This interface requires passing an ISugarQueryable type instead of an IQueryable type. How can this change be made?

![image](https://github.com/casbin/Casbin.NET/assets/54492956/c155c57a-9d63-440c-a55b-5539a6ffab3e)

**Comment by hsluoyz** [comment]
@Muzi999 why close?

**Comment by huazhikui** [comment]
Hey there!  Essentially, we're trying to keep things more generic in our code, which means not tying ourselves too closely to any specific types from SqlSugar, like with the `IPolicyFilter`. It's all about keeping our options open and making sure we're not locking ourselves into a corner. I hope that makes sense! Really appreciate you bringing this up, and it’s great having everyone chipping in with their thoughts.
