### ISSUE TITLE
Use semantic-release to automatically release Casbin.NET versions

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#37]
We already used semantic-release in Go and Nodejs, see Node-Casbin: https://github.com/casbin/node-casbin/pull/153#issuecomment-625775348

![image](https://user-images.githubusercontent.com/3787410/83984606-7aca6980-a968-11ea-8eef-49f5fbd45008.png)

There's also a student working on Java: https://github.com/casbin/jcasbin/issues/76

I think we should also integrate it into .NET. It will auto-release to GitHub Releases and Nuget. We need to find a plugin to use semantic-release in .NET project. I found these but not tried any one yet, maybe useful for you:

- https://spectrum.chat/semantic-release/general/is-semantic-release-only-for-nodejs-project~d73935a1-fa4b-4287-8410-845062dba82e
- https://github.com/axlj45/dotnet-semantic-release
- https://github.com/mdetweil/sempack

Can anyone work on it?

**Comment by hsluoyz** [comment]
@xcaptain @huazhikui @nodece @Sagilio can you take the issue?

**Comment by xcaptain** [comment]
EFCore-Adapter can automatically release when new tag was created. https://github.com/casbin-net/EFCore-Adapter/blob/master/.travis.yml#L40

I think we don't need to release so frequently, manually release is OK.

**Comment by hsluoyz** [comment]
I think currently only @huazhikui is familiar with the .NET release instructions. @huazhikui can you release a version from master now?

**Comment by Sagilio** [comment]
Azure DevOps has a [release pipeline](https://dev.azure.com/Casbin/Casbin.NET/_release) that can automatically release the package.
We can use [Git Version](https://gitversion.net/docs/) to complete the version.
I have tried about it, The [build result](https://dev.azure.com/Sagilio/Casbin.NET.Test/_build/results?buildId=15&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=e82b3e12-88cd-5514-86b1-e3d861ec93fa) is like this :

![image](https://user-images.githubusercontent.com/42855245/84489410-44784b80-acd4-11ea-9615-d540649ce422.png)

**Comment by hsluoyz** [comment]
@Sagilio I want GitHub & Nuget releases, is it OK for these?

**Comment by Sagilio** [comment]
> @Sagilio I want GitHub & Nuget releases, is it OK for these?

It has [Github releases Task](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) and Nuget Command Task which can push package.
Almost All the tasks can be used at both the build and release pipeline.

**Comment by hsluoyz** [comment]
@Sagilio good, go ahead with this way. Let me know if you need any help.

**Comment by hsluoyz** [comment]
Any update?

**Comment by Sagilio** [comment]
> Any update?

I tried to auto-release some version:

1.2.8 : [Build result](https://dev.azure.com/Sagilio/Casbin.NET.Test/_build/results?buildId=46&view=logs&j=e7e95e74-12bf-5ad2-fcbc-6c3f1acb24e8)
1.2.9 : [Build result](https://dev.azure.com/Sagilio/Casbin.NET.Test/_build/results?buildId=47&view=logs&j=e7e95e74-12bf-5ad2-fcbc-6c3f1acb24e8)
1.3.0-alpha0045 : [Build result](https://dev.azure.com/Sagilio/Casbin.NET.Test/_build/results?buildId=48&view=logs&j=e7e95e74-12bf-5ad2-fcbc-6c3f1acb24e8)

[Azure pipeline build history](https://dev.azure.com/Sagilio/Casbin.NET.Test/_build?definitionId=4)
[Github release list](https://github.com/Sagilio/Casbin.NET/releases)

Should we how to trigger the release pipeline? The way of most used looks to use develop branch and trigger when pull request from that.

**Comment by hsluoyz** [comment]
@nodece @huazhikui @xcaptain

**Comment by xcaptain** [comment]
Nice, the `buildAndPack` works, the next step is to determine when to trigger `buildAndPack`. But how can the semantic release bot change the version number at https://github.com/casbin/Casbin.NET/blob/master/NetCasbin/NetCasbin.csproj#L11

**Comment by Sagilio** [comment]
> Nice, the `buildAndPack` works, the next step is to determine when to trigger `buildAndPack`. But how can the semantic release bot change the version number at https://github.com/casbin/Casbin.NET/blob/master/NetCasbin/NetCasbin.csproj#L11

It can be set at the command `dotnet build /p:FileVersion=1.3.0.0` and I have released a version ([1.3.1](https://github.com/Sagilio/Casbin.NET/releases/tag/1.3.1))

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/Casbin.NET/issues/65

**Comment by hsluoyz** [comment]
I don't think this issue is actually getting fixed. Just merged a PR: https://github.com/casbin/Casbin.NET/pull/123 but I didn't see a new release coming (like v1.4.0 -> v1.4.1)

@Sagilio need resolving.

**Comment by Sagilio** [comment]
@hsluoyz  According to the current release strategy, the new version of the package will be released to multiple places according to its type.
Dev release: it will be released to the MyGet source by every commit, the last version is [here](https://www.myget.org/feed/casbin-net/package/nuget/Casbin.NET/1.4.0-build.69.master.cefb330).
Beta release: it will be released to the NuGet source as a prerelease.
Stable release: it will be released to the NuGet source as a stable release. 
This strategy is popular at the .NET library repo.

Do we need to remove the dev release channel and release a new stable version by every 
 commit, it will like the go casbin repo?

**Comment by hsluoyz** [comment]
@Sagilio good to know the current release workflow! Yeah, I think the current formal release frequency is too low and it would be better if we can use the Go-Casbin similar way: we will even release a new formal release for a bug fix PR merge, but we will embrace semantic-versioning to indicate the nature of the change. For example:

1. Big breaking change: `v1.2.3` --> `v2.0.0`
2. New feature: `v1.2.3` --> `v1.3.0`
3. Bug fix: `v1.2.3` --> `v1.2.4`

It's notable that this will also help our popularization as some social media accounts will announce the new releases for important packages.

**Comment by Sagilio** [comment]
@hsluoyz Ok, I will try to use a similar way of Go-Casbin.
