### ISSUE TITLE
Support load policy text from adapter

### ISSUE THREAD

**Issue by sagilio** [casbin/Casbin.NET#371]
> my model and policy are like this: [#367 (comment)](https://github.com/casbin/Casbin.NET/issues/367#issuecomment-2333998981) it gets passed in the string format itself. also, do we need the DefaultFileContentAdapter class now?

It need not now. we will add new API for it.

_Originally posted by @sagilio in https://github.com/casbin/Casbin.NET/issues/366#issuecomment-2365017684_

**Comment by mitesh-diligencevault** [comment]
@tangyang9464 @sagilio When are we planning to release this?

**Comment by sagilio** [comment]
> @tangyang9464 @sagilio When are we planning to release this?

This feature is scheduled to be released this week.

**Comment by mitesh-diligencevault** [comment]
@tangyang9464 @sagilio Is this released?
