### ISSUE TITLE
Where is the documentation for creating custom IAdapters?

### ISSUE THREAD

**Issue by Tilation** [casbin/Casbin.NET#375]
I can't find anything about creating custom IAdapters, I need to create one to load the rules but there is no documentation for how to implement IAdapter and the methods and parameter names don't match with the ones in the existing documentation for another programming languages.

**Comment by hsluoyz** [comment]
@Tilation refer to other adapter implementations: https://github.com/casbin-net?q=adapter&type=all&language=&sort=
