### ISSUE TITLE
Should we need to avoid repeated checking policy exists when call AddPolicy

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#38]
When we add policy by `Enforcer`, It will call the `AddPolicy` method like this:
```csharp
protected bool AddPolicy(string sec, string ptype, List<string> rule)
{
    if (model.HasPolicy(sec, ptype, rule))
    {
        return false;
    }
    ...
    var ruleAdded = model.AddPolicy(sec, ptype, rule);
    return ruleAdded;
}
```
But when calling `model.AddPolicy` it will check again the policy exists like this:
```csharp
public bool AddPolicy(string sec, string ptype, List<string> rule)
{
    if (!HasPolicy(sec, ptype, rule))
    {
        Model[sec][ptype].Policy.Add(rule);
        return true;
    }
    return false;
}
```
I think we should avoid repeated checking. but the `AddPolicy` method in `Policy` class is a public method. If we modify the existing implementation, It will cause unsafe calling. We can create an internal method without check to avoid it.

**Comment by hsluoyz** [comment]
We should add a map to make check policy existence O(1).

**Comment by hsluoyz** [comment]
@Sagilio can you make a PR?

**Comment by Sagilio** [comment]
> @Sagilio can you make a PR?

Ok.

**Comment by Sagilio** [comment]
I have tried about it in this version and it has the almost same performance. So I think the issue can be closed.
