### ISSUE TITLE
Use constant to replace the repeated string at code

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#41]
We can use some const or read-only field to replace the string like `"g"`, `"p"` and use `String.Empty` and `Array.Empty` to replace `""`, `new string[]`. I think it will make the code more maintainable.

**Comment by huazhikui** [comment]
good idea, can you fix it? @Sagilio

**Comment by Sagilio** [comment]
Ok, but It will have a lot of conflicts with the pull request #40, I will fix and open a pull request later than that one.
