### ISSUE TITLE
Fix the IO exception when sometimes running unit tests

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#47]
It like the [build result](https://dev.azure.com/Casbin/Casbin.NET/_build/results?buildId=60&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7bfb7e0f-549d-5929-c603-6e8046613b9e).

I think we have two plans to fix it:

1.  Provide some same test files for the async tests.
2.  Refactor the unit test project and use some fixtures to make loading files is not inside of the unit test body.

**Comment by hsluoyz** [comment]
Good finding! We should not copy test files with the same content.
