### ISSUE TITLE
A demo project on how to use casbin with efcore

### ISSUE THREAD

**Issue by xcaptain** [casbin/Casbin.NET#5]
Hello, Thank you for this awesome project, I have been using this project for more than 1 month, it works well but sadly lack an official efcore adapter, some discussions can be found at https://github.com/casbin/Casbin.NET/issues/4 . I created a sample project at https://github.com/xcaptain/CasbinTestProj it contains my setup for my private project. If you want I think I can help create an efcore adapter.

**Comment by hsluoyz** [comment]
Hi @xcaptain , thanks for the amazing code. I think it can be a good starting point for an official EF adapter. I have created a new official repo here: https://github.com/casbin-net/EFCore-Adapter . Can you migrate your code there?

**Comment by hsluoyz** [comment]
Moreover, please join our Tencent QQ group: https://casbin.org/en/help

**Comment by xcaptain** [comment]
I made a pull request at https://github.com/casbin-net/EFCore-Adapter/pull/1 please take a look, thanks.

**Comment by hsluoyz** [comment]
Nearly finished.
