### ISSUE TITLE
Develop Casbin.AspNetCore to help use Casbin in ASP NET Core

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#51]
.ASP NET Core is a free cross-platform open-source and the most popular framework for building web apps and services with .NET and C# now. We need to provide fine support to it. 

#### Description about the `Casbin.AspNetCore`
It is an extension package for anyone to can use Casbin in ASP NET Core easily.
It will extend from the `Microsoft.AspNetCore.Authorization`. So It can be compatible with the existing authorization config. And it is also the first step of [casbin-sam](https://github.com/casbin-net/casbin-sam).

I think we can create a new repository named 'Casbin.AspNetCore' to develop it.

#### Related issue:
#24

**Comment by Sagilio** [comment]
@hsluoyz Can you help me create the repository and give me the write permission?

**Comment by hsluoyz** [comment]
Created: https://github.com/casbin-net/Casbin.AspNetCore

![image](https://user-images.githubusercontent.com/3787410/86420381-0c7b8b80-bd09-11ea-993b-4accc9c8d16c.png)

**Comment by harsimranb** [comment]
@Sagilio Can you share a little bit on how Casbin.AspNetCore will work?  How it will take advantage of Authorization libraries in Asp.Net Core?  I am quite intrigued about the integration you've mentioned.

**Comment by hsluoyz** [comment]
@harsimranb please send issue to the repo: https://github.com/casbin-net/Casbin.AspNetCore
