### ISSUE TITLE
Change the workflow of creating a model

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#52]
1. I think we should move the `NewModel` API to Model class. It will follow the [go implement](https://github.com/casbin/casbin/blob/master/model/model.go).
It will be some break changes if we directly delete them, So we can set Obsolete at on them now and remove at the next mainline version.
2. Move the ModelPath field to Model class as a property.  It will we can get the model path when instantiating the Enforcer by model and adapter. It will not any users.
3. Add required section check.

**Comment by hsluoyz** [comment]
@Sagilio yes, please follow the Go's Casbin way.
