### ISSUE TITLE
Change the way of integrating RBAC API and Management API to a one Enforcer

### ISSUE THREAD

**Issue by Sagilio** [casbin/Casbin.NET#56]
I think the best way to integrate IEnforcer (rbac api) and ManagementEnforcer (management api) to a one IEnforcer is use `Extension Method` to implement it. Here are some reasons:
1. IEnforcer can be a simple and clean interface.
2. We can maintain the RBAC and Management API at different class, and we can easy to add new helper type API.
4. Follow the CARP desgin.

It will become a break change, we should change the protect field to Read-only property (also GetModel method can do it) and delete the `InternalEnforcer`, `ManagementEnforcer` and `CoreEnforcer` and convert them to a Enforcer class which only includes the API in `InternalEnforcer` and `CoreEnforcer` in now version).

**Relate comment:**
https://github.com/casbin/Casbin.NET/pull/55#issuecomment-662766747

**Comment by hsluoyz** [comment]
Why does it have breaking change?

**Comment by Sagilio** [comment]
> Why does it have breaking change?

Beacause the InternalEnforcer, ManagementEnforcer and CoreEnforcer class are public. If someone use them in the code, it will can not pass the compiling.

**Comment by huazhikui** [comment]
Agree with you, I think that the `IManagementEnforcer`   don't need inherit `ICoreEnforcer`,  it only need to include `management api`.  through `Extension Method `  integrate `rbac api` and `management api`.  We can also add some decorator class to implement it.

**Comment by hsluoyz** [comment]
Good.
