### ISSUE TITLE
Remove Coveralls Repo Token from Appveyor definition

### ISSUE THREAD

**Issue by rdpetrusek** [casbin/Casbin.NET#6]
I see a token in the appveyor definition file. I'd guess it's a security concern, but I don't know what access is available through that token.

**Comment by huazhikui** [comment]
the token is used to access coveralls.io and upload coverage data to coveralls

**Comment by huazhikui** [comment]
> I see a token in the appveyor definition file. I'd guess it's a security concern, but I don't know what access is available through that token.

the token is used to access coveralls.io and upload coverage data to coveralls

**Comment by hsluoyz** [comment]
Maybe it's better to put the key into Travis portal directly.
