### ISSUE TITLE
DynamicExpresso.Exceptions.UnknownIdentifierException: 'Unknown identifier 'keyMatch4' (at index 65).

### ISSUE THREAD

**Issue by mitesh-diligencevault** [casbin/Casbin.NET#61]
KeyMatch4 is not supported, can we pls add the support?

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain @Sagilio can you fix it?

**Comment by hsluoyz** [comment]
@huazhikui please release a new version, so @mitesh-diligencevault can use!

**Comment by mitesh-diligencevault** [comment]
@huazhikui when will this be available on Nuget to use?

**Comment by huazhikui** [comment]
@mitesh-diligencevault `Casbin.net` v1.3.1 has been released on `nuget.org`
