### ISSUE TITLE
Auto publish package on Github Actions

### ISSUE THREAD

**Issue by huazhikui** [casbin/Casbin.NET#65]
Auto publish package on Github Actions when we add new  version tag. 

[publish](https://github.com/casbin/Casbin.NET/packages)

**Comment by hsluoyz** [comment]
@Sagilio can you do this?

**Comment by Sagilio** [comment]
I plan to use Azure DevOps's release pipeline to handle all release work, this work can be completed with the #37 issue. 
The benchmark will run on Github Actions because I think we should use the same environment to compare with others.

Now, I do not have the edit permission in Azure DevOps.

**Comment by Sagilio** [comment]
We need not the Azure DevOps release pipeline now. we will handle all publish task with GitHub Actions.

**Comment by hsluoyz** [comment]
@huazhikui @Sagilio why didn't I see any new automated release triggered by this PR?

**Comment by huazhikui** [comment]
because we haven't a new tag @hsluoyz

**Comment by hsluoyz** [comment]
Can you make a new tag like `v1.3.2` to test it?
