### ISSUE TITLE
Signing the assembly

### ISSUE THREAD

**Issue by andreasthalmann** [casbin/Casbin.NET#9]
It seems the assembly distributed with the nuget package is not signed, this makes it not very handy to reference Casbin.Net from a signed assembly.

**Comment by hsluoyz** [comment]
@huazhikui @xgenvn

**Comment by hsluoyz** [comment]
Hi @andreasthalmann , I browsed the price of Microsoft Authenticode cert, it's so expensive (~$500 for one year), like this one: https://trustcenter.websecurity.symantec.com/process/trust/productOptions?productType=SoftwareValidationClass3

Am I seeing the correct type of cert? Is there any cheaper options?

And what causes you trouble specifically by using an un-signed package?

**Comment by andreasthalmann** [comment]
There is no need for a code signing certificate from an official authority. Create a “casbin.snk” key using the strong name tool (sn.exe from sdk) and use it for signing the casbin assemblies.
see also https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name and/or
https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair
if not signed you get at build time
CSC : warning CS8002: Referenced assembly 'NetCasbin, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
and at runtime
System.IO.FileLoadException: Could not load file or assembly 'NetCasbin, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

It’s good idea to sign

**Comment by huazhikui** [comment]
the assembly  is signed in version v1.2.2

**Comment by hsluoyz** [comment]
Good job. Thanks for everyone !
