### ISSUE TITLE
Unknown identifier 'eval' problem

### ISSUE THREAD

**Issue by tzengshinfu** [casbin/Casbin.NET#91]
Hi, folks:

I get the problem when using ABAC.
![Image 009](https://user-images.githubusercontent.com/2170033/93410786-3be37280-f8cc-11ea-9ca4-45d1d4abf80c.png)

the link below is my project that issue happened.
https://github.com/tzengshinfu/TestCasbinNet

**Comment by hsluoyz** [comment]
@Sagilio can you take a look?

/cc @huazhikui @xcaptain @nodece

**Comment by Sagilio** [comment]
@tzengshinfu  The feature has been included in the master branch, but we do not release it, you can try to build the code the test it or wait for the next release. We will release the new version soon.

**Comment by hsluoyz** [comment]
@huazhikui @Sagilio please make a new release.

**Comment by hsluoyz** [comment]
@tzengshinfu released v1.4.0: https://github.com/casbin/Casbin.NET/releases/tag/v1.4.0
